### ISSUE TITLE
Webapp malfunction

### ISSUE THREAD

**Issue by tupuni** [clld/pofatu#3]
In the "samples" page (https://pofatu.clld.org/values), the functionality that allows to search per region does not screen the database: instead of showing results of a query, it still provides the whole list of samples in the db. 
Similarly, when selecting a point on the map the same thing happens. example: if i select the Island "Rapa iti" (at https://pofatu.clld.org/languages/australrapaitianaruabay), the whole list of samples is displayed and not just the samples from that Island.

**Comment by xrotwang** [comment]
As far as I can tell, the issue is still present.

**Comment by tupuni** [comment]
Yes, I closed this issue because I opened issue #7 there: https://github.com/pofatu/pofatu-data/issues/7

**Comment by xrotwang** [comment]
Ah. I see. But here's the better place for website issues, because this is the repository where the source code of the app is kept. So changes in the code here will address the issues here.

**Comment by tupuni** [comment]
Ok, got it! I'll reopen the issues about the web app here then.

**Comment by xrotwang** [comment]
Nope. I already fixed it :), see above

**Comment by tupuni** [comment]
Yes I saw that, great thanks! 
I "forwarded" issue #5 Updates to the web app in this repository
