### ISSUE TITLE
[webapp-content_about-updated270120.pdf](https://github.com/pofatu/pofatu-data/files/4117360/webapp-content_about-updated270120.pdf)

### ISSUE THREAD

**Issue by tupuni** [clld/pofatu#4]
[webapp-content_about-updated270120.pdf](https://github.com/pofatu/pofatu-data/files/4117360/webapp-content_about-updated270120.pdf)

Current content of the "About" section of the web app needs to be modified with the following text file, which provides an updated URL for citation of the Pofatu db, but still contains non definitive parts, specifically:
- the two mentions of [hyperlink] should be replaced by the actual links to the Data Submission Template and the Guidelines to data submission (that I will upload to the 'doc' file of the pofatu-data repository)
- can we distribute the following contact email: 'pofatu@shh.mpg.de'? Whatever address we use, let's delete "(or whatever it is)".

_Originally posted by @Tupuni in https://github.com/pofatu/pofatu-data/issues/5#issuecomment-578752962_

**Comment by tupuni** [comment]
https://github.com/pofatu/pofatu-data/issues/5#issuecomment-579282179
https://github.com/pofatu/pofatu-data/issues/5#issuecomment-579337579

**Comment by tupuni** [comment]
I just spotted an error and a couple of changes to make on the welcome page.  where is the best place for me to tell you what to modify?

**Comment by xrotwang** [comment]
A new issue in this repos.

Tupuni <notifications@github.com> schrieb am Di., 28. Jan. 2020, 19:22:
