### ISSUE TITLE
Zenodo DOI at https://pofatu.clld.org/download

### ISSUE THREAD

**Issue by tupuni** [clld/pofatu#6]
@xrotwang 
currently the DOI provided at https://pofatu.clld.org/download is: 10.5281/zenodo.3608862
should be changed to : 10.5281/zenodo.3628155.

**Comment by xrotwang** [comment]
Ah, no, 10.5281/zenodo.3628155 is just the python package. The data isn't actually released yet (so the DOI in the web page is just a placeholder), see https://github.com/pofatu/pofatu-data/releases
But I can make a release as soon as you think the [README](https://github.com/pofatu/pofatu-data/blob/master/README.md) for the data is sufficient.
